spring:
  application:
    name: starter
langchain4j:
  open-ai:
    streaming-chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4
      temperature: 0
      strict-tools: true
    embedding-model:
      api-key: ${OPENAI_API_KEY}
